// 권한
export const ROLE = {
  MASTER: 'ROLE_MASTER',
  GENERAL_ADMIN: 'ROLE_GENERAL_ADMIN',
  RESPONSIBLE_ADMIN: 'ROLE_RESPONSIBLE_ADMIN',
  FRANCHISE: 'ROLE_FRANCHISE',
  DELIVERY: 'ROLE_DELIVERY',
};
export const HEAD_QUARTER_ROLES = [ROLE.MASTER, ROLE.GENERAL_ADMIN, ROLE.RESPONSIBLE_ADMIN];
export const ALL_ROLES = [...HEAD_QUARTER_ROLES, ROLE.FRANCHISE, ROLE.DELIVERY];

// 직급
export const POSITION = {
  STAFF: 'STAFF',
  ASSISTANT_MANAGER: 'ASSISTANT_MANAGER',
  MANAGER: 'MANAGER',
  CEO: 'CEO',
};
export const POSITIONS = [POSITION.STAFF, POSITION.ASSISTANT_MANAGER, POSITION.MANAGER, POSITION.CEO];
export const APPROVAL_POSITIONS = [POSITION.ASSISTANT_MANAGER, POSITION.MANAGER, POSITION.CEO];

// 기안자의 주문/교환/반품 승인 여부
export const DRAFTER_APPROVED = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  NONE: 'NONE',
};

// 주문/교환/반품 전체 결재 상태
export const APPROVAL = {
  APPROVED: 'APPROVED',
  CANCELED: 'CANCELED',
  UNCONFIRMED: 'UNCONFIRMED',
  REJECTED: 'REJECTED',
};

export const EXCHANGE_REASON = {
  DAMAGED: 'DAMAGED',
  DEFECTIVE: 'DEFECTIVE',
  OTHER: 'OTHER',
};

// 교환 상태
export const EXCHANGE_STATUS = {
  REQUESTED: 'REQUESTED',
  PENDING: 'PENDING',
  CANCELED: 'CANCELED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PICKING: 'PICKING',
  PICKED: 'PICKED',
  SHIPPING: 'SHIPPING',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
};

// 주문 상태
export const ORDER_STATUS = {
  REQUESTED: 'REQUESTED',
  PENDING: 'PENDING',
  CANCELED: 'CANCELED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SHIPPING: 'SHIPPING',
  SHIPPED: 'SHIPPED',
};

// 발주 상태
export const PURCHASE_STATUS = {
  REQUESTED: 'REQUESTED',
  CANCELED: 'CANCELED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

// 결재라인 종류
export const APPROVAL_KIND = {
  PURCHASE: 'PURCHASE',
  ORDER: 'ORDER',
  EXCHANGE: 'EXCHANGE',
  RETURN: 'RETURN',
};

// 결재상태
export const APPROVAL_STATUS = {
  UNCONFIRMED: 'UNCONFIRMED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};
