// 권한
export const HEAD_QUARTER_ROLES = ['ROLE_MASTER', 'ROLE_GENERAL_ADMIN', 'ROLE_RESPONSIBLE_ADMIN'];
export const ALL_ROLES = [...HEAD_QUARTER_ROLES, 'ROLE_FRANCHISE', 'ROLE_DELIVERY'];

// 직급
export const POSITIONS = ['STAFF', 'ASSISTANT_MANAGER', 'MANAGER', 'CEO'];
